input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:log_message}"
    }
  }

  date {
    match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
  }
}
# curl -k -u elastic:hNMXDW4JjWMod13iSdec https://localhost:9200
output {
   elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "hNMXDW4JjWMod13iSdec"
    ssl_enabled => true
    ssl_verification_mode => "none"

    index => "hello-logs"
  }

  stdout {
    codec => rubydebug
  }
}
